### PR TITLE
Updated READ.me with .gif

### PR DESCRIPTION
**Pull request by emilyy1231**
Issue #11 

Updated with .gif, but I need to find a larger and more high quality gif maker. Let me know if the idea/placement in READ.me is ok with you though!

### CODE REVIEW

**Comment by LucasLeandro1204** [comment]
@emilyy1231 Thanks emily, but you can record only the widget not the entire page, and the gif is too fast.
About the placement, just don't worry, I will change it when I code more snippets xd

**Comment by LucasLeandro1204** [comment]
And maybe put the gif in a static folder inside the project instead of uploading it in external services??

**Comment by emilyy1231** [comment]
@LucasLeandro1204 Yeah, of course. I can make those changes. 
So... 
1.) Larger + higher quality + slower gif
2.) Record just widget 
3.) gif inside static project 
I'll see if I can get to it tonight, but I'm a bit busy. I'll probably do it tomorrow. If somebody else hits you up, I'm totally fine with it.

**Comment by LucasLeandro1204** [comment]
Relax, take your time =)
The gif quality is ok, but recording just the widget will be better

**Pull request closed without merging**
